on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

name: test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/cache@v1
        id: node-cache
        with:
          path: node_modules
          key: |
            12.x-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            12.x-
      - run: npm ci
        if: steps.node-cache.outputs.cache-hit != 'true'
      - run: npm test
        env:
          CI: true
